[tool.poetry]
name = "singlecell-kaggle"
version = "0.1.0"
description = ""
authors = ["Luke Schiefelbein <luke.schiefelbein@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.6"
pandas = "^1.4.3"
seaborn = "^0.11.2"
tables = "^3.7.0"
matplotlib = "3.5.1"
sklearn = "^0.0"
scipy = "^1.9.1"
h5py = "^3.7.0"
hdf5plugin = "^3.3.1"
fastparquet = "^0.8.3"
pyarrow = "^9.0.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.7.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
